# Assignment - Basic Pandas
<sup>Created by Natawut Nupairoj, Department of Computer Engineering, Chulalongkorn University</sup>

Using pandas to explore youtube trending data from GB (GBvideos.csv and GB_category_id.json) and answer the questions.

In [2]:
import pandas as pd
import numpy as np

To simplify data retrieval process on Colab, we heck if we are in the Colab environment and download data files from a shared drive and save them in folder "data".

For those using jupyter notebook on the local computer, you can read data directly assuming you save data in the folder "data".

In [3]:
# for colab
"""

import sys
import subprocess

# Check if running on Google Colab
IN_COLAB = 'google.colab' in sys.modules

if IN_COLAB:
    # Specific commands for Google Colab
    !wget https://github.com/kaopanboonyuen/2110446_DataScience_2021s2/raw/main/datasets/data.tgz -O data.tgz
    !tar -xzvf data.tgz
else:
    # Commands for local machine, such as VSCode
    subprocess.run(["wget", "https://github.com/kaopanboonyuen/2110446_DataScience_2021s2/raw/main/datasets/data.tgz", "-O", "data.tgz"], check=True)
    subprocess.run(["tar", "-xzvf", "data.tgz"], check=True)
"""

'\n\nimport sys\nimport subprocess\n\n# Check if running on Google Colab\nIN_COLAB = \'google.colab\' in sys.modules\n\nif IN_COLAB:\n    # Specific commands for Google Colab\n    !wget https://github.com/kaopanboonyuen/2110446_DataScience_2021s2/raw/main/datasets/data.tgz -O data.tgz\n    !tar -xzvf data.tgz\nelse:\n    # Commands for local machine, such as VSCode\n    subprocess.run(["wget", "https://github.com/kaopanboonyuen/2110446_DataScience_2021s2/raw/main/datasets/data.tgz", "-O", "data.tgz"], check=True)\n    subprocess.run(["tar", "-xzvf", "data.tgz"], check=True)\n'

## How many rows are there in the GBvideos.csv after removing duplications?

https://sparkbyexamples.com/pandas/pandas-find-unique-values-from-columns/

https://www.geeksforgeeks.org/python-pandas-dataframe-drop_duplicates/

In [4]:
df = pd.read_csv('./data/GBvideos.csv')
df

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,Jw1Y-zhQURU,17.14.11,John Lewis Christmas Ad 2017 - #MozTheMonster,John Lewis,26,2017-11-10T07:38:29.000Z,"christmas|""john lewis christmas""|""john lewis""|...",7224515,55681,10247,9479,https://i.ytimg.com/vi/Jw1Y-zhQURU/default.jpg,False,False,False,Click here to continue the story and make your...
1,3s1rvMFUweQ,17.14.11,Taylor Swift: …Ready for It? (Live) - SNL,Saturday Night Live,24,2017-11-12T06:24:44.000Z,"SNL|""Saturday Night Live""|""SNL Season 43""|""Epi...",1053632,25561,2294,2757,https://i.ytimg.com/vi/3s1rvMFUweQ/default.jpg,False,False,False,Musical guest Taylor Swift performs …Ready for...
2,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787420,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...
3,PUTEiSjKwJU,17.14.11,Goals from Salford City vs Class of 92 and Fri...,Salford City Football Club,17,2017-11-13T02:30:38.000Z,"Salford City FC|""Salford City""|""Salford""|""Clas...",27833,193,12,37,https://i.ytimg.com/vi/PUTEiSjKwJU/default.jpg,False,False,False,Salford drew 4-4 against the Class of 92 and F...
4,rHwDegptbI4,17.14.11,Dashcam captures truck's near miss with child ...,Cute Girl Videos,25,2017-11-13T01:45:13.000Z,[none],9815,30,2,30,https://i.ytimg.com/vi/rHwDegptbI4/default.jpg,False,False,False,Dashcam captures truck's near miss with child ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38911,l884wKofd54,18.14.06,Enrique Iglesias - MOVE TO MIAMI (Official Vid...,EnriqueIglesiasVEVO,10,2018-05-09T07:00:01.000Z,"Enrique Iglesias feat. Pitbull|""MOVE TO MIAMI""...",25066952,268088,12783,9933,https://i.ytimg.com/vi/l884wKofd54/default.jpg,False,False,False,NEW SONG - MOVE TO MIAMI feat. Pitbull (Click ...
38912,IP8k2xkhOdI,18.14.06,Jacob Sartorius - Up With It (Official Music V...,Jacob Sartorius,10,2018-05-11T17:09:16.000Z,"jacob sartorius|""jacob""|""up with it""|""jacob sa...",1492219,61998,13781,24330,https://i.ytimg.com/vi/IP8k2xkhOdI/default.jpg,False,False,False,THE OFFICIAL UP WITH IT MUSIC VIDEO!Get my new...
38913,Il-an3K9pjg,18.14.06,Anne-Marie - 2002 [Official Video],Anne-Marie,10,2018-05-08T11:05:08.000Z,"anne|""marie""|""anne-marie""|""2002""|""two thousand...",29641412,394830,8892,19988,https://i.ytimg.com/vi/Il-an3K9pjg/default.jpg,False,False,False,Get 2002 by Anne-Marie HERE ▶ http://ad.gt/200...
38914,-DRsfNObKIQ,18.14.06,Eleni Foureira - Fuego - Cyprus - LIVE - First...,Eurovision Song Contest,24,2018-05-08T20:32:32.000Z,"Eurovision Song Contest|""2018""|""Lisbon""|""Cypru...",14317515,151870,45875,26766,https://i.ytimg.com/vi/-DRsfNObKIQ/default.jpg,False,False,False,Eleni Foureira represented Cyprus at the first...
38915,4YFo4bdMO8Q,18.14.06,KYLE - Ikuyo feat. 2 Chainz & Sophia Black [A...,SuperDuperKyle,10,2018-05-11T04:06:35.000Z,"Kyle|""SuperDuperKyle""|""Ikuyo""|""2 Chainz""|""Soph...",607552,18271,274,1423,https://i.ytimg.com/vi/4YFo4bdMO8Q/default.jpg,False,False,False,Debut album 'Light of Mine' out now: http://ky...

## 1. df.shape and .unique() for counting number of unique value for each column

In [4]:
df.shape

(38916, 16)

In [5]:
print(df['video_id'])
print(len(df['video_id']))

0        Jw1Y-zhQURU
1        3s1rvMFUweQ
2        n1WpP7iowLc
3        PUTEiSjKwJU
4        rHwDegptbI4
            ...
38911    l884wKofd54
38912    IP8k2xkhOdI
38913    Il-an3K9pjg
38914    -DRsfNObKIQ
38915    4YFo4bdMO8Q
Name: video_id, Length: 38916, dtype: object
38916

In [6]:
print(df['video_id'].unique())
print(len(df['video_id'].unique()))

['Jw1Y-zhQURU' '3s1rvMFUweQ' 'n1WpP7iowLc' ... 'V15BYnSr0P8' 'BOhylL90UVQ'
 '14G7Qw5DC9M']
3272

In [7]:
df_noduplicate = df.drop_duplicates()
df_noduplicate

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,Jw1Y-zhQURU,17.14.11,John Lewis Christmas Ad 2017 - #MozTheMonster,John Lewis,26,2017-11-10T07:38:29.000Z,"christmas|""john lewis christmas""|""john lewis""|...",7224515,55681,10247,9479,https://i.ytimg.com/vi/Jw1Y-zhQURU/default.jpg,False,False,False,Click here to continue the story and make your...
1,3s1rvMFUweQ,17.14.11,Taylor Swift: …Ready for It? (Live) - SNL,Saturday Night Live,24,2017-11-12T06:24:44.000Z,"SNL|""Saturday Night Live""|""SNL Season 43""|""Epi...",1053632,25561,2294,2757,https://i.ytimg.com/vi/3s1rvMFUweQ/default.jpg,False,False,False,Musical guest Taylor Swift performs …Ready for...
2,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787420,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...
3,PUTEiSjKwJU,17.14.11,Goals from Salford City vs Class of 92 and Fri...,Salford City Football Club,17,2017-11-13T02:30:38.000Z,"Salford City FC|""Salford City""|""Salford""|""Clas...",27833,193,12,37,https://i.ytimg.com/vi/PUTEiSjKwJU/default.jpg,False,False,False,Salford drew 4-4 against the Class of 92 and F...
4,rHwDegptbI4,17.14.11,Dashcam captures truck's near miss with child ...,Cute Girl Videos,25,2017-11-13T01:45:13.000Z,[none],9815,30,2,30,https://i.ytimg.com/vi/rHwDegptbI4/default.jpg,False,False,False,Dashcam captures truck's near miss with child ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38911,l884wKofd54,18.14.06,Enrique Iglesias - MOVE TO MIAMI (Official Vid...,EnriqueIglesiasVEVO,10,2018-05-09T07:00:01.000Z,"Enrique Iglesias feat. Pitbull|""MOVE TO MIAMI""...",25066952,268088,12783,9933,https://i.ytimg.com/vi/l884wKofd54/default.jpg,False,False,False,NEW SONG - MOVE TO MIAMI feat. Pitbull (Click ...
38912,IP8k2xkhOdI,18.14.06,Jacob Sartorius - Up With It (Official Music V...,Jacob Sartorius,10,2018-05-11T17:09:16.000Z,"jacob sartorius|""jacob""|""up with it""|""jacob sa...",1492219,61998,13781,24330,https://i.ytimg.com/vi/IP8k2xkhOdI/default.jpg,False,False,False,THE OFFICIAL UP WITH IT MUSIC VIDEO!Get my new...
38913,Il-an3K9pjg,18.14.06,Anne-Marie - 2002 [Official Video],Anne-Marie,10,2018-05-08T11:05:08.000Z,"anne|""marie""|""anne-marie""|""2002""|""two thousand...",29641412,394830,8892,19988,https://i.ytimg.com/vi/Il-an3K9pjg/default.jpg,False,False,False,Get 2002 by Anne-Marie HERE ▶ http://ad.gt/200...
38914,-DRsfNObKIQ,18.14.06,Eleni Foureira - Fuego - Cyprus - LIVE - First...,Eurovision Song Contest,24,2018-05-08T20:32:32.000Z,"Eurovision Song Contest|""2018""|""Lisbon""|""Cypru...",14317515,151870,45875,26766,https://i.ytimg.com/vi/-DRsfNObKIQ/default.jpg,False,False,False,Eleni Foureira represented Cyprus at the first...
38915,4YFo4bdMO8Q,18.14.06,KYLE - Ikuyo feat. 2 Chainz & Sophia Black [A...,SuperDuperKyle,10,2018-05-11T04:06:35.000Z,"Kyle|""SuperDuperKyle""|""Ikuyo""|""2 Chainz""|""Soph...",607552,18271,274,1423,https://i.ytimg.com/vi/4YFo4bdMO8Q/default.jpg,False,False,False,Debut album 'Light of Mine' out now: http://ky...

In [8]:
df_noduplicate.shape

(38745, 16)

## 2. value counts and nan value

In [9]:
df_noduplicate['category_id'].value_counts()

category_id
10    13700
24     9055
22     2923
1      2564
26     1928
17     1903
23     1820
20     1778
25     1218
15      533
28      516
27      457
2       144
19       96
29       90
43       20
Name: count, dtype: int64

In [10]:
print(type(df_noduplicate['category_id'].value_counts()))

<class 'pandas.core.series.Series'>

In [11]:
df.isna().sum()

video_id                    0
trending_date               0
title                       0
channel_title               0
category_id                 0
publish_time                0
tags                        0
views                       0
likes                       0
dislikes                    0
comment_count               0
thumbnail_link              0
comments_disabled           0
ratings_disabled            0
video_error_or_removed      0
description               612
dtype: int64

## 3. statistic value

In [12]:
print(df_noduplicate['views'].mean())
print(df_noduplicate['views'].sum())
print(df_noduplicate['views'].min())
print(df_noduplicate['views'].max())
print(df_noduplicate['views'].mode())

5911292.647515808
229033033628
851
424538912
0    191321
Name: views, dtype: int64

In [13]:
print(df_noduplicate['views'].idxmin())
print(df_noduplicate['views'].idxmax())

3477
28412

## 4. loc and iloc

first index filter row, second filter column

In [14]:
df_noduplicate.iloc[:, 3:7]

,channel_title,category_id,publish_time,tags
0,John Lewis,26,2017-11-10T07:38:29.000Z,"christmas|""john lewis christmas""|""john lewis""|..."
1,Saturday Night Live,24,2017-11-12T06:24:44.000Z,"SNL|""Saturday Night Live""|""SNL Season 43""|""Epi..."
2,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In..."
3,Salford City Football Club,17,2017-11-13T02:30:38.000Z,"Salford City FC|""Salford City""|""Salford""|""Clas..."
4,Cute Girl Videos,25,2017-11-13T01:45:13.000Z,[none]
...,...,...,...,...
38911,EnriqueIglesiasVEVO,10,2018-05-09T07:00:01.000Z,"Enrique Iglesias feat. Pitbull|""MOVE TO MIAMI""..."
38912,Jacob Sartorius,10,2018-05-11T17:09:16.000Z,"jacob sartorius|""jacob""|""up with it""|""jacob sa..."
38913,Anne-Marie,10,2018-05-08T11:05:08.000Z,"anne|""marie""|""anne-marie""|""2002""|""two thousand..."
38914,Eurovision Song Contest,24,2018-05-08T20:32:32.000Z,"Eurovision Song Contest|""2018""|""Lisbon""|""Cypru..."
38915,SuperDuperKyle,10,2018-05-11T04:06:35.000Z,"Kyle|""SuperDuperKyle""|""Ikuyo""|""2 Chainz""|""Soph..."

In [15]:
df_noduplicate.loc[:, ['channel_title', 'publish_time']]

                    channel_title              publish_time
0                      John Lewis  2017-11-10T07:38:29.000Z
1             Saturday Night Live  2017-11-12T06:24:44.000Z
2                      EminemVEVO  2017-11-10T17:00:03.000Z
3      Salford City Football Club  2017-11-13T02:30:38.000Z
4                Cute Girl Videos  2017-11-13T01:45:13.000Z
...                           ...                       ...
38911         EnriqueIglesiasVEVO  2018-05-09T07:00:01.000Z
38912             Jacob Sartorius  2018-05-11T17:09:16.000Z
38913                  Anne-Marie  2018-05-08T11:05:08.000Z
38914     Eurovision Song Contest  2018-05-08T20:32:32.000Z
38915              SuperDuperKyle  2018-05-11T04:06:35.000Z

[38745 rows x 2 columns]


## 5. filter by condition and drop_duplicates

||.     How many VDO's that contain at least one record (row) of "dislikes" more than "likes"?  <font color=red>DO NOT group by the data and make sure that you count only unique title!</font>



<font color=red>most of methods in dataframe are not replace old value you need to use new dataframe to store the value or you need to assign value to your datafame or you can use inplace=True!</font>

https://www.geeksforgeeks.org/python-pandas-dataframe-drop_duplicates/

In [16]:
len(df['title'].unique())

3369

In [17]:
import pandas as pd
filtered_df = df[df['dislikes'] > df['likes']]

unique_videos_df = filtered_df.drop_duplicates(subset='title')

print(unique_videos_df.shape)
print(unique_videos_df.shape[0])

(56, 16)
56

## How many VDO that are trending on 22 Jan 2018 with comments more than 10,000 comments?

search command : pandas dataframe filter by condition

link : https://sparkbyexamples.com/pandas/pandas-filter-rows-by-conditions/

In [18]:
print(type(df['trending_date'][0]))
print(type(df['comment_count'][0]))

<class 'str'>
<class 'numpy.int64'>

In [19]:
df_t_10000 = df.loc[(df['trending_date'] == '18.22.01') & (df['comment_count'] > 10000)]
df_t_10000

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
13392,WAwRrtH-4Lg,18.22.01,My Horibal Speling,TheOdd1sOut,23,2018-01-20T17:15:48.000Z,"spelling|""school""|""teacher""|""speech""|""audioboo...",5686453,334806,3787,70565,https://i.ytimg.com/vi/WAwRrtH-4Lg/default.jpg,False,False,False,hOI guis!!1! Thx 4 wathcing my vid abuot my ho...
13394,Y-iFgDK_D5s,18.22.01,The Smallest Bird you have ever seen,A Chick Called Albert,15,2018-01-21T00:10:07.000Z,"wren|""baby bird""|""incubating""|""nest""|""birdnest...",1481728,64757,1015,10121,https://i.ytimg.com/vi/Y-iFgDK_D5s/default.jpg,False,False,False,By accident I got hold of two of the smallest ...
13397,lrWRy9BBp-c,18.22.01,ELDERS REACT TO UGANDAN KNUCKLES MEMES,FBE,24,2018-01-19T22:00:02.000Z,"ugandan knuckles memes|""ugandan knuckles""|""uga...",1874710,54224,4897,14099,https://i.ytimg.com/vi/lrWRy9BBp-c/default.jpg,False,False,False,Ugandan Knuckles Memes reacted to by Elders! O...
13398,_7985zBEM3o,18.22.01,Primitive Technology: A-frame hut,Primitive Technology,22,2018-01-19T21:09:10.000Z,[none],3702942,161760,1414,13839,https://i.ytimg.com/vi/_7985zBEM3o/default.jpg,False,False,False,I built an A frame hut as a large work space f...
13411,liczsmUSMA4,18.22.01,"J. Balvin, Jeon, Anitta - Machika",jbalvinVEVO,10,2018-01-19T05:00:01.000Z,"J Balvin|""Official Video""|""Machika""|""Anitta""|""...",24103517,777582,63601,69932,https://i.ytimg.com/vi/liczsmUSMA4/default.jpg,False,False,False,"J BALVIN, ANITTA, JEON “MACHIKA” \nhttps://UML..."
13416,M4vnmgZLA8s,18.22.01,Justin Timberlake - Supplies (Official Video),justintimberlakeVEVO,10,2018-01-18T13:00:02.000Z,"Justin Timberlake|""Pop""|""RCA Records Label""|""S...",6246329,161214,17874,16688,https://i.ytimg.com/vi/M4vnmgZLA8s/default.jpg,False,False,False,Supplies from Man of the Woods\nOfficial Music...
13421,sGIm0-dQd8M,18.22.01,Dura - Daddy Yankee (Video Oficial),Daddy Yankee,10,2018-01-18T22:32:49.000Z,"daddy yankee reggaeton|""daddy yankee youtube""|...",19687431,467428,15859,30151,https://i.ytimg.com/vi/sGIm0-dQd8M/default.jpg,False,False,False,Dura - Daddy Yankee - nuevo video oficial 2018...
13427,eACohWVwTOc,18.22.01,The Chainsmokers - Sick Boy,ChainsmokersVEVO,10,2018-01-17T15:00:02.000Z,"Dance|""Disruptor Records/Columbia""|""Sick Boy""|...",10073675,439795,14741,25895,https://i.ytimg.com/vi/eACohWVwTOc/default.jpg,False,False,False,Sick Boy Out Now: http://smarturl.it/SickBoy\n...
13442,oRSVrtKph_k,18.22.01,BTS Exclusive Interview #BTSonBBCR1,BBC Radio 1,10,2018-01-19T05:00:03.000Z,"BTS|""K-Pop""|""Bangtan""|""Adele""|""BBC Radio1""|""Mr...",1294987,153336,606,13998,https://i.ytimg.com/vi/oRSVrtKph_k/default.jpg,False,False,False,BBC Radio1's Adele Roberts has been tracking t...
13452,aMcjxSThD54,18.22.01,"Jordan Peterson debate on the gender pay gap, ...",Channel 4 News,25,2018-01-16T17:13:07.000Z,"Jordan peterson|""jordan peterson interview""|""J...",2796465,111162,2295,56852,https://i.ytimg.com/vi/aMcjxSThD54/default.jpg,False,False,False,"Channel 4 News’ full, fiery interview with cli..."
13457,V0HCZ4YGqbw,18.22.01,La de da de da de da de day oh,bill wurtz,22,2018-01-16T20:34:48.000Z,"bill wurtz|""song""|""music""|""la de da de da de d...",3001349,284097,6026,32926,https://i.ytimg.com/vi/V0HCZ4YGqbw/default.jpg,False,False,False,http://billwurtz.com\n\n\n\npatreon: http://p...
13470,S0nbOenwCLw,18.22.01,Kodak Black - Roll In Peace feat. XXXTentacion...,Kodak Black,10,2018-01-15T19:04:29.000Z,"Kodak Black|""Roll In Peace""|""Project Baby 2""|""...",7926997,249662,8732,23537,https://i.ytimg.com/vi/S0nbOenwCLw/default.jpg,False,False,False,Kodak Black - Roll In Peace feat. XXXTENTACION...
13480,M1fKcktiPuk,18.22.01,"BHAD BHABIE Hi Bich REMIX ft YBN Nahmir, Rich ...",Bhad Bhabie,10,2018-01-16T21:43:04.000Z,"danielle bregoli|""cash me ousside""|""cash me ou...",1110742,76306,2109,10456,https://i.ytimg.com/vi/M1fKcktiPuk/default.jpg,False,False,False,👋🏻 BHAD BHABIE formerly Danielle Bregoli HI BI...
13484,uexk7jWXYmU,18.22.01,[MV] JBJ _ My Flower (꽃이야),1theK (원더케이),10,2018-01-17T09:00:07.000Z,"Kpop|""1theK""|""원더케이""|""loen""|""로엔""|""뮤비""|""티져""|""MV""...",2361687,196603,997,13915,https://i.ytimg.com/vi/uexk7jWXYmU/default.jpg,False,False,False,[MV] JBJ _ My Flower (꽃이야)\n\n*English subtitl...
13508,yHHnywiSwIE,18.22.01,The Top Dan Memes of 2017,Daniel Howell,22,2018-01-14T23:15:00.000Z,"the top dan memes of 2017|""the""|""top""|""dan""|""m...",1918225,228494,993,31919,https://i.ytimg.com/vi/yHHnywiSwIE/default.jpg,False,False,False,Before we move on towards a hopeful future let...
13513,Xo8FPXlI3CU,18.22.01,Stray Kids 어린 날개 Performance Video,jypentertainment,10,2018-01-15T15:00:03.000Z,"Stray Kids|""스트레이 키즈""|""방찬""|""김우진""|""이민호""|""서창빈""|""황...",1624259,168834,922,10169,https://i.ytimg.com/vi/Xo8FPXlI3CU/default.jpg,False,False,False,Stray Kids 어린 날개 Performance Video\n\nFind Str...
13515,ijUK3z5rt5s,18.22.01,I said Gucci Gang 1000000 Times. Here are the ...,Graham The Christian,23,2018-01-14T06:22:22.000Z,"red nose day|""gucci gang""|""gucci gang stream""|...",2359694,67529,8185,12923,https://i.ytimg.com/vi/ijUK3z5rt5s/default.jpg,False,False,False,All proceeds from this stream went to https://...
13525,Mgfe5tIwOj0,18.22.01,Dua Lipa - IDGAF (Official Music Video),Dua Lipa,10,2018-01-12T12:00:07.000Z,"dua lipa|""idgaf""|""dl1""|""I don't give a fuck""|""...",37071502,1393373,38001,57527,https://i.ytimg.com/vi/Mgfe5tIwOj0/default.jpg,False,False,False,Dua Lipa - IDGAF: https://wbr.ec/idgaf\n\nArti...
13530,I5uXtODq74w,18.22.01,Where have we been?,h3h3Productions,24,2018-01-12T22:44:07.000Z,"where have we been?|""where has h3h3 been""|""h3h...",3621293,286440,8458,33178,https://i.ytimg.com/vi/I5uXtODq74w/default.jpg,False,False,False,We haven't been posting many videos the past m...
13531,dfnCAmr569k,18.22.01,"Taylor Swift - End Game ft. Ed Sheeran, Future",TaylorSwiftVEVO,10,2018-01-12T05:00:01.000Z,"Taylor|""Swift""|""End""|""Game""|""Big""|""Machine""|""Pop""",55575589,1949684,110044,152187,https://i.ytimg.com/vi/dfnCAmr569k/default.jpg,False,False,False,Music video by Taylor Swift performing End Gam...
13533,gu9_m0vm7fM,18.22.01,Enrique Iglesias - EL BAÑO ft. Bad Bunny,EnriqueIglesiasVEVO,10,2018-01-12T08:00:02.000Z,"Enrique Iglesias feat. Bad Bunny Music|""Enriqu...",43072421,748035,85740,53571,https://i.ytimg.com/vi/gu9_m0vm7fM/default.jpg,False,False,False,LISTEN & DOWNLOAD:\n \nSpotify - http://smartu...
13536,b7K_lbglfI4,18.22.01,Marshmello x Lil Peep - Spotlight [Official Au...,marshmello,10,2018-01-12T02:13:27.000Z,"marshmello|""lil peep""|""marshmello lil peep""|""l...",7012583,329106,5392,26863,https://i.ytimg.com/vi/b7K_lbglfI4/default.jpg,False,False,False,Marshmello x Lil Peep - Spotlight\nPurchase & ...
13546,FVRPzwb1Vi4,18.22.01,Natti Natasha ❌ Bad Bunny - Amantes de Una No...,Pina Records,10,2018-01-11T21:01:26.000Z,"pina records|""natti natasha""|""bad bunny""|""aman...",51829439,740093,72084,42946,https://i.ytimg.com/vi/FVRPzwb1Vi4/default.jpg,False,False,False,Natti Natasha X Bad Bunny - Amantes de Una Noc...
13547,YXTzMOmmEfE,18.22.01,Hayley Kiyoko - Curious [Official Video],Hayley Kiyoko,10,2018-01-11T21:28:39.000Z,"Curious|""Expectations""|""Hayley Kiyoko""|""Sleep ...",3239412,173857,2171,10048,https://i.ytimg.com/vi/YXTzMOmmEfE/default.jpg,False,False,False,Curious Available Now! Download or stream at: ...
13553,I7B0z_2EZmQ,18.22.01,Regarding the rumors about me today,shane,23,2018-01-10T22:13:19.000Z,"shanedawsontv|""shane""|""dawson""|""vlogs""|""iphone...",6295614,605511,9316,205410,https://i.ytimg.com/vi/I7B0z_2EZmQ/default.jpg,False,False,False,.
13559,wQ_POfToaVY,18.22.01,TWICE「Candy Pop」Music Video,TWICE JAPAN OFFICIAL YouTube Channel,10,2018-01-11T15:00:03.000Z,"TWICE|""Candy Pop""",16408127,437902,29408,53872,https://i.ytimg.com/vi/wQ_POfToaVY/default.jpg,False,False,False,TWICE JAPAN 2nd SINGLE『Candy Pop』\n2018.02.07 ...
13563,lVNt1sUWyDU,18.22.01,"Quality Control, Quavo, Nicki Minaj - She For ...",QualityControlVEVO,10,2018-01-09T17:00:05.000Z,"QC|""Quality Control""|""Control The Streets""|""Qu...",8102209,201561,13554,11863,https://i.ytimg.com/vi/lVNt1sUWyDU/default.jpg,False,False,False,Quality Control's Control The Streets Vol. 1 i...
13578,P6ODTQKhaXk,18.22.01,Dunkey's Best of 2017,videogamedunkey,20,2018-01-09T20:30:01.000Z,"dunkey top 10|""top 10 games 2017""|""dunkey top ...",4704560,207679,3482,12859,https://i.ytimg.com/vi/P6ODTQKhaXk/default.jpg,False,False,False,My favorite games of 2017 (and 2016).\n\nExpan...

In [20]:
df_t_10000.shape

(28, 16)

In [21]:
df_t_10000.shape[0]

28

## 6. using group by -> for operation ex. sum, avg

In [22]:
df_try = df.loc[(df['trending_date'] == '17.01.12') ]
df_try

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
3398,6ZfuNTqbHE8,17.01.12,Marvel Studios' Avengers: Infinity War Officia...,Marvel Entertainment,24,2017-11-29T13:26:24.000Z,"marvel|""comics""|""comic books""|""nerdy""|""geeky""|...",56367282,2157730,34077,303178,https://i.ytimg.com/vi/6ZfuNTqbHE8/default.jpg,False,False,False,There was an idea… Avengers: Infinity War. In ...
3399,nx1R-eHSkfM,17.01.12,The New Snapchat in 60 Seconds,Snapchat,10,2017-11-29T14:00:03.000Z,"new snapchat|""version 2""|""snap inc""|""brandnew""...",1894443,0,0,0,https://i.ytimg.com/vi/nx1R-eHSkfM/default.jpg,True,True,False,"Evan Spiegel, co-founder and CEO, explains the..."
3400,8z_cg5CypRc,17.01.12,Kelly Clarkson Carpool Karaoke,The Late Late Show with James Corden,24,2017-11-30T06:30:56.000Z,"James Corden|""The Late Late Show""|""Colbert""|""l...",3074263,96530,1011,7415,https://i.ytimg.com/vi/8z_cg5CypRc/default.jpg,False,False,False,James asks Kelly Clarkson to help him carpool ...
3401,WeyLEe1T0yo,17.01.12,Why cities are full of uncomfortable benches,Vox,25,2017-11-29T12:30:01.000Z,"vox.com|""vox""|""explain""|""hostile architecture""...",1183611,30250,1863,3429,https://i.ytimg.com/vi/WeyLEe1T0yo/default.jpg,False,False,False,That bench won't be yours forever.\n\nSubscrib...
3402,7AXo-bYGXI4,17.01.12,Sam Smith - One Last Song (Official Video),SamSmithWorldVEVO,10,2017-11-29T12:00:00.000Z,"Sam|""Smith""|""One""|""Last""|""Song""|""Capitol""|""Pop""",2222937,132072,1350,5870,https://i.ytimg.com/vi/7AXo-bYGXI4/default.jpg,False,False,False,One Last Song' taken from Sam Smith’s new albu...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3591,hq9SEUlkZ5s,17.01.12,My Very POSITIVE Birth Plan | MOTHERHOOD,Sprinkleofglitter,26,2017-11-18T13:22:53.000Z,"sprinkleofglitter|""sprinkle of glitter""|""Louis...",167077,7833,167,626,https://i.ytimg.com/vi/hq9SEUlkZ5s/default.jpg,False,False,False,A very old school production video detailing m...
3592,lMSHTnkVJVs,17.01.12,Rae Sremmurd - Perplexing Pegasus,RaeSremmurdVEVO,10,2017-11-17T17:00:09.000Z,"Rae Sremmurd|""Rap""|""Hip-Hop""|""Mike Will Made i...",7268812,170210,4253,6752,https://i.ytimg.com/vi/lMSHTnkVJVs/default.jpg,False,False,False,Perplexing Pegasus Out Now! http://smarturl.it...
3593,1ihTE5cxUCQ,17.01.12,Charles Manson - Cease To Exist,leftways,10,2015-09-29T11:03:27.000Z,"Charles Manson (Composer)|""Cease To Exist (Mus...",96286,753,54,221,https://i.ytimg.com/vi/1ihTE5cxUCQ/default.jpg,False,False,False,"Charles Manson's Cease To Exist, the song that..."
3594,coOKvrsmQiI,17.01.12,RAMPAGE - OFFICIAL TRAILER 1 [HD],Warner Bros. Pictures,24,2017-11-16T21:15:08.000Z,"Rampage|""Rampage the Movie""|""The Rock""|""Dwayne...",19678970,162345,14147,27912,https://i.ytimg.com/vi/coOKvrsmQiI/default.jpg,False,False,False,"In Theaters April 20, 2018\n\nwww.RampageTheMo..."
3595,X9Gc_g638C8,17.01.12,BTS Talks Emojis and More at the 2017 AMAs | E...,E! Live from the Red Carpet,24,2017-11-20T03:14:59.000Z,"2017 American Music Awards|""Awards""|""Red Carpe...",111441,5242,23,414,https://i.ytimg.com/vi/X9Gc_g638C8/default.jpg,False,False,False,The Korean-pop boy band opens up about their f...

In [23]:
df_group = df.groupby('trending_date')
df_group.first().head()

,video_id,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
trending_date,,,,,,,,,,,,,,,
17.01.12,6ZfuNTqbHE8,Marvel Studios' Avengers: Infinity War Officia...,Marvel Entertainment,24,2017-11-29T13:26:24.000Z,"marvel|""comics""|""comic books""|""nerdy""|""geeky""|...",56367282,2157730,34077,303178,https://i.ytimg.com/vi/6ZfuNTqbHE8/default.jpg,False,False,False,There was an idea… Avengers: Infinity War. In ...
17.02.12,6ZfuNTqbHE8,Marvel Studios' Avengers: Infinity War Officia...,Marvel Entertainment,24,2017-11-29T13:26:24.000Z,"marvel|""comics""|""comic books""|""nerdy""|""geeky""|...",66637636,2331353,41153,316185,https://i.ytimg.com/vi/6ZfuNTqbHE8/default.jpg,False,False,False,There was an idea… Avengers: Infinity War. In ...
17.03.12,SA7AIQw-7Ms,G-Eazy & Halsey - Him & I (Official Video),GEazyMusicVEVO,10,2017-12-01T16:15:00.000Z,"BPG/RVG/RCA Records|""G-Eazy & Halsey""|""Him & I...",3853829,257472,3468,11131,https://i.ytimg.com/vi/SA7AIQw-7Ms/default.jpg,False,False,False,New Album ‘The Beautiful & Damned’ Available E...
17.04.12,1l26UFQ06eQ,Welcome to Hell - SNL,Saturday Night Live,24,2017-12-03T05:52:22.000Z,"SNL|""Saturday Night Live""|""SNL Season 43""|""Epi...",2358350,34132,3534,5446,https://i.ytimg.com/vi/1l26UFQ06eQ/default.jpg,False,False,False,"Women (Saoirse Ronan, Cecily Strong, Kate McKi..."
17.05.12,dsNNfiA6qjs,"Nick Crompton - JAKE PAUL, TEAM 10 & MARTINEZ ...",Caspar,24,2017-12-04T18:58:55.000Z,"nick crompton|""jake""|""paul""|""logan""|""every""|""d...",587061,39323,2485,2836,https://i.ytimg.com/vi/dsNNfiA6qjs/default.jpg,False,False,False,"I spoke to Team 10 COO, Nick Crompton about hi..."

In [24]:
df_group.last().head()

,video_id,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
trending_date,,,,,,,,,,,,,,,
17.01.12,X9Gc_g638C8,BTS Talks Emojis and More at the 2017 AMAs | E...,E! Live from the Red Carpet,24,2017-11-20T03:14:59.000Z,"2017 American Music Awards|""Awards""|""Red Carpe...",111441,5242,23,414,https://i.ytimg.com/vi/X9Gc_g638C8/default.jpg,False,False,False,The Korean-pop boy band opens up about their f...
17.02.12,8mCcM-PUmLM,I Dressed Like It Was 1977,Safiya Nygaard,22,2017-11-19T21:29:25.000Z,"i dressed like it was 1977|""1977 fashions""|""19...",2434870,120702,1439,10223,https://i.ytimg.com/vi/8mCcM-PUmLM/default.jpg,False,False,False,I styled 3 outfits inspired by the popular fas...
17.03.12,jpl2X8tDfIA,Are you really surprised you're here?,Wiggy,10,2017-11-21T02:17:12.000Z,"Nate|""Wiegman""|""lil peep""|""gustav ahr""|""downto...",425974,18155,111,1287,https://i.ytimg.com/vi/jpl2X8tDfIA/default.jpg,False,False,False,I love you Gus. Interview by Mezzy\nSong: Down...
17.04.12,_akwfRuL4os,Highlights of the EA predatory behavior announ...,Chris Lee,22,2017-11-21T19:29:03.000Z,[none],318386,9383,238,2224,https://i.ytimg.com/vi/_akwfRuL4os/default.jpg,False,False,False,The State of Hawaii announces action to addres...
17.05.12,RP3UsFrDJfY,Lady Gaga - The Cure (Live On The American Mus...,LadyGagaVEVO,10,2017-11-22T00:04:08.000Z,"Lady|""Gaga""|""The""|""Cure""|""AMAs""|""American""|""Mu...",1938197,79966,1308,5009,https://i.ytimg.com/vi/RP3UsFrDJfY/default.jpg,False,False,False,GET THE CURE:\nhttp://gaga.lk/TheCure\n\nGET “...

In [25]:
print(type(df_group))

<class 'pandas.core.groupby.generic.DataFrameGroupBy'>

Which date that has the minimum average number of comments per VDO?

https://www.geeksforgeeks.org/python-pandas-dataframe-groupby/

In [26]:
# Calculating the average number of comments per video for each trending date
average_comments = df.groupby('trending_date')['comment_count'].mean()

# Finding the trending date with the minimum average number of comments
min_average_date = average_comments.idxmin()
min_average_value = average_comments.min()

min_average_date, min_average_value

('17.15.11', 4738.673366834171)

## Compare "Sports" and "Comady", how many days that there are more total daily views of VDO in "Sports" category than in "Comady" category?

In [27]:
# Assuming 'category_id' corresponds to categories, with 'Sports' and 'Comedy' having specific IDs
# Replace these IDs with the actual ones corresponding to 'Sports' and 'Comedy' in your DataFrame
sports_category_id = 17  # Example ID for Sports, replace with actual ID
comedy_category_id = 23  # Example ID for Comedy, replace with actual ID

# Filtering the DataFrame for Sports and Comedy categories
sports_df = df[df['category_id'] == sports_category_id]
comedy_df = df[df['category_id'] == comedy_category_id]

# Grouping by trending date and summing views for each category
sports_views = sports_df.groupby('trending_date')['views'].sum()
comedy_views = comedy_df.groupby('trending_date')['views'].sum()

# Combining the two series into a DataFrame
combined_views = pd.DataFrame({'Sports': sports_views, 'Comedy': comedy_views})

# Counting the days where Sports category has more views than Comedy category
days_more_sports_views = (combined_views['Sports'] > combined_views['Comedy']).sum()

days_more_sports_views

49

## 7. pandas series -> when select single column of pandas series, it is pandas series, when select multiples column, it is pandas dataframe

In [28]:
print(type(df_noduplicate))
print(type(df_noduplicate.loc[:, ['channel_title', 'publish_time']]))
print(type(df_noduplicate.iloc[:, 3:5]))
print()

print(type(df_noduplicate['publish_time']))
print(type(df_noduplicate.iloc[:, 3]))

df_noduplicate.loc[:, ['channel_title', 'publish_time']].head()

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>

<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>

                channel_title              publish_time
0                  John Lewis  2017-11-10T07:38:29.000Z
1         Saturday Night Live  2017-11-12T06:24:44.000Z
2                  EminemVEVO  2017-11-10T17:00:03.000Z
3  Salford City Football Club  2017-11-13T02:30:38.000Z
4            Cute Girl Videos  2017-11-13T01:45:13.000Z

In [29]:
df_noduplicate['publish_time']

0        2017-11-10T07:38:29.000Z
1        2017-11-12T06:24:44.000Z
2        2017-11-10T17:00:03.000Z
3        2017-11-13T02:30:38.000Z
4        2017-11-13T01:45:13.000Z
                   ...
38911    2018-05-09T07:00:01.000Z
38912    2018-05-11T17:09:16.000Z
38913    2018-05-08T11:05:08.000Z
38914    2018-05-08T20:32:32.000Z
38915    2018-05-11T04:06:35.000Z
Name: publish_time, Length: 38745, dtype: object

In [30]:
print(type(df_noduplicate))
print(type(df.isna()))
print(type(df.isna().mean()))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>

In [31]:
print(type(df_noduplicate['channel_title']))
print()
df_noduplicate['channel_title']

<class 'pandas.core.series.Series'>

0                        John Lewis
1               Saturday Night Live
2                        EminemVEVO
3        Salford City Football Club
4                  Cute Girl Videos
                    ...
38911           EnriqueIglesiasVEVO
38912               Jacob Sartorius
38913                    Anne-Marie
38914       Eurovision Song Contest
38915                SuperDuperKyle
Name: channel_title, Length: 38745, dtype: object

## 8. create dataframe and series

In [32]:
import pandas as pd

# a simple list
list = [1,2,3,4,5]

# create series form a list
ser = pd.Series(list)
print(type(ser))
print(ser)

<class 'pandas.core.series.Series'>
0    1
1    2
2    3
3    4
4    5
dtype: int64

In [33]:
filtered = ser[ser > 3]
filtered_index = ser[ser > 3].index

print(type(filtered))
print(filtered)
print()

print(type(filtered_index))
print(filtered_index)
print()

print(filtered_index[0])

<class 'pandas.core.series.Series'>
3    4
4    5
dtype: int64

<class 'pandas.core.indexes.base.Index'>
Index([3, 4], dtype='int64')

3

search command : create dataframe pandas

link : https://www.geeksforgeeks.org/different-ways-to-create-pandas-dataframe/

In [5]:
list1 = [1,2,3,4,5]
list2 = [5,4,3,2,1]

list_of_tuples = list(zip(list1, list2))
 
# Assign data to tuples.
list_of_tuples
 
 
# Converting lists of tuples into
# pandas Dataframe.
df = pd.DataFrame(list_of_tuples,
                  columns=['list1', 'list2'])
df

   list1  list2
0      1      5
1      2      4
2      3      3
3      4      2
4      5      1

## 9. dataframe.apply and lamda function, create dataframe, statistic (quantile, percentile)

lamda function -> params, return

In [34]:
x = lambda a : a + 10
print(x(5))

15

In [35]:
x = lambda a, b : a * b
print(x(5, 6))

30

In [36]:

# Import pandas library
import pandas as pd

# initialize list of lists
data = [['tom', 10], ['nick', 15], ['juli', 14], ['aug', 12], ['tnn', 35]]

# Create the pandas DataFrame
df = pd.DataFrame(data, columns=['Name', 'Age'])

df

   Name  Age
0   tom   10
1  nick   15
2  juli   14
3   aug   12
4   tnn   35

In [37]:
Q1 = df['Age'].quantile(0.75)
Q1

15.0

In [38]:
df['Age'] = df['Age'].apply(lambda x : min(Q1*2, x))

In [39]:
df

   Name   Age
0   tom  10.0
1  nick  15.0
2  juli  14.0
3   aug  12.0
4   tnn  30.0