# Part1 get data

In [35]:
import pandas as pd

In [36]:
df_train = pd.read_csv('./data/house-prices-advanced-regression-techniques/train.csv')
df_test = pd.read_csv('./data/house-prices-advanced-regression-techniques/test.csv')

In [37]:
df_train.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [38]:
df_test.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal

# part2 visualize (simple)

In [39]:
df_train.isna().sum()

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
                ...
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 81, dtype: int64

In [40]:
df_test.isna().sum()

Id                 0
MSSubClass         0
MSZoning           4
LotFrontage      227
LotArea            0
                ...
MiscVal            0
MoSold             0
YrSold             0
SaleType           1
SaleCondition      0
Length: 80, dtype: int64

check all nan cols : find all nan columns pandas

link : https://stackoverflow.com/questions/36226083/how-to-find-which-columns-contain-any-nan-value-in-pandas-dataframe

In [41]:
train_nan_cols = df_train.columns[df_train.isna().any()].tolist()

In [42]:
test_nan_cols = df_test.columns[df_test.isna().any()].tolist()

In [43]:
all_nan_cols = train_nan_cols
for i in test_nan_cols :
    if i in train_nan_cols :
        pass
    else :
        all_nan_cols.append(i)
print(len(all_nan_cols), all_nan_cols)

34 ['LotFrontage', 'Alley', 'MasVnrType', 'MasVnrArea', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Electrical', 'FireplaceQu', 'GarageType', 'GarageYrBlt', 'GarageFinish', 'GarageQual', 'GarageCond', 'PoolQC', 'Fence', 'MiscFeature', 'MSZoning', 'Utilities', 'Exterior1st', 'Exterior2nd', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'BsmtFullBath', 'BsmtHalfBath', 'KitchenQual', 'Functional', 'GarageCars', 'GarageArea', 'SaleType']

In [44]:
all_nan_cols.append("Id")

# part3 preprocess (simple)

## 3.1 drop cols

search command : drop multiple column pandas

link : https://www.geeksforgeeks.org/how-to-drop-one-or-multiple-columns-in-pandas-dataframe/

In [45]:
def drop_cols(df, cols) :
    df_copy = df.copy()
    df_copy = df_copy.drop(cols, axis=1)
    return df_copy

In [46]:
df_train_without_nan = drop_cols(df_train, all_nan_cols)
df_test_without_nan = drop_cols(df_test, all_nan_cols)

In [47]:
df_train_without_nan.head()

,MSSubClass,LotArea,Street,LotShape,LandContour,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,...,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleCondition,SalePrice
0,60,8450,Pave,Reg,Lvl,Inside,Gtl,CollgCr,Norm,Norm,...,61,0,0,0,0,0,2,2008,Normal,208500
1,20,9600,Pave,Reg,Lvl,FR2,Gtl,Veenker,Feedr,Norm,...,0,0,0,0,0,0,5,2007,Normal,181500
2,60,11250,Pave,IR1,Lvl,Inside,Gtl,CollgCr,Norm,Norm,...,42,0,0,0,0,0,9,2008,Normal,223500
3,70,9550,Pave,IR1,Lvl,Corner,Gtl,Crawfor,Norm,Norm,...,35,272,0,0,0,0,2,2006,Abnorml,140000
4,60,14260,Pave,IR1,Lvl,FR2,Gtl,NoRidge,Norm,Norm,...,84,0,0,0,0,0,12,2008,Normal,250000

In [48]:
df_test_without_nan.head()

,MSSubClass,LotArea,Street,LotShape,LandContour,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleCondition
0,20,11622,Pave,Reg,Lvl,Inside,Gtl,NAmes,Feedr,Norm,...,140,0,0,0,120,0,0,6,2010,Normal
1,20,14267,Pave,IR1,Lvl,Corner,Gtl,NAmes,Norm,Norm,...,393,36,0,0,0,0,12500,6,2010,Normal
2,60,13830,Pave,IR1,Lvl,Inside,Gtl,Gilbert,Norm,Norm,...,212,34,0,0,0,0,0,3,2010,Normal
3,60,9978,Pave,IR1,Lvl,Inside,Gtl,Gilbert,Norm,Norm,...,360,36,0,0,0,0,0,6,2010,Normal
4,120,5005,Pave,IR1,HLS,Inside,Gtl,StoneBr,Norm,Norm,...,0,82,0,0,144,0,0,1,2010,Normal

search command : delete all categorical columns pandas

link : https://stackoverflow.com/questions/12725417/drop-non-numeric-columns-from-a-pandas-dataframe

In [49]:
df_train_without_nan_numerical_only = df_train_without_nan.select_dtypes(['number'])
df_train_without_nan_numerical_only.head()

,MSSubClass,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
0,60,8450,7,5,2003,2003,856,854,0,1710,...,0,61,0,0,0,0,0,2,2008,208500
1,20,9600,6,8,1976,1976,1262,0,0,1262,...,298,0,0,0,0,0,0,5,2007,181500
2,60,11250,7,5,2001,2002,920,866,0,1786,...,0,42,0,0,0,0,0,9,2008,223500
3,70,9550,7,5,1915,1970,961,756,0,1717,...,0,35,272,0,0,0,0,2,2006,140000
4,60,14260,8,5,2000,2000,1145,1053,0,2198,...,192,84,0,0,0,0,0,12,2008,250000

In [50]:
df_test_without_nan_numerical_only = df_test_without_nan.select_dtypes(['number'])
df_test_without_nan_numerical_only.head()

,MSSubClass,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,...,Fireplaces,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold
0,20,11622,5,6,1961,1961,896,0,0,896,...,0,140,0,0,0,120,0,0,6,2010
1,20,14267,6,6,1958,1958,1329,0,0,1329,...,0,393,36,0,0,0,0,12500,6,2010
2,60,13830,5,5,1997,1998,928,701,0,1629,...,1,212,34,0,0,0,0,0,3,2010
3,60,9978,6,6,1998,1998,926,678,0,1604,...,1,360,36,0,0,0,0,0,6,2010
4,120,5005,8,5,1992,1992,1280,0,0,1280,...,0,0,82,0,0,144,0,0,1,2010

## 3.2 train test split (train, val)

from your titanic notebook

In [51]:
target_col = "SalePrice"
train_features_X = df_train_without_nan_numerical_only.loc[:, df_train_without_nan_numerical_only.columns != target_col]
train_features_y = df_train_without_nan_numerical_only[target_col]

In [52]:
from sklearn.model_selection import train_test_split

X_train, X_Val, y_train, y_val = train_test_split(train_features_X, train_features_y, test_size=0.10, random_state=42)

In [53]:
X_train.head()

,MSSubClass,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,...,Fireplaces,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold
907,50,11500,7,7,1936,1987,1020,1037,0,2057,...,1,0,0,0,0,322,0,0,6,2006
782,20,16285,7,5,2001,2002,1430,0,0,1430,...,0,0,33,0,0,0,0,0,6,2009
952,85,7200,5,8,1972,2003,768,0,0,768,...,0,192,0,0,0,0,0,0,4,2009
620,30,8248,3,3,1914,1950,864,0,0,864,...,0,0,0,100,0,0,0,0,9,2008
669,30,11600,4,5,1922,1950,1180,0,0,1180,...,1,0,0,67,0,0,0,0,7,2006

In [54]:
X_Val.head()

,MSSubClass,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,...,Fireplaces,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold
892,20,8414,6,8,1963,2003,1068,0,0,1068,...,0,192,0,0,0,0,0,0,2,2006
1105,60,12256,8,5,1994,1995,1500,1122,0,2622,...,2,186,32,0,0,0,0,0,4,2010
413,30,8960,5,6,1927,1950,1028,0,0,1028,...,1,0,0,130,0,0,0,0,3,2010
522,50,5000,6,7,1947,1950,1004,660,0,1664,...,2,0,24,36,0,0,0,0,10,2006
1036,20,12898,9,5,2007,2008,1620,0,0,1620,...,1,228,0,0,0,0,0,0,9,2009

In [55]:
y_train.head()

907    250000
782    187100
952    133900
620     67000
669    137500
Name: SalePrice, dtype: int64

In [56]:
y_val.head()

892     154500
1105    325000
413     115000
522     159000
1036    315500
Name: SalePrice, dtype: int64

# 4. Model

## 4.1 decision tree regressor

search command : decision tree regression model

link : https://scikit-learn.org/stable/auto_examples/tree/plot_tree_regression.html

In [57]:
from sklearn.tree import DecisionTreeRegressor

In [58]:
regressor = DecisionTreeRegressor(max_depth=10)
regressor.fit(X_train, y_train)

DecisionTreeRegressor(max_depth=10)

In [59]:
eval_predicted = regressor.predict(X_Val)
eval_predicted

array([140444.44444444, 340000.        , 100840.32258065, 133206.25      ,
       321500.        ,  85700.        , 205000.        , 156877.5       ,
        77250.        , 130069.23076923, 166937.5       , 118350.325     ,
        67000.        , 157000.        , 182697.43589744, 118350.325     ,
       200200.453125  , 143194.59459459, 100840.32258065, 180878.35      ,
       103800.        , 215166.66666667, 173790.25      , 118350.325     ,
       200200.453125  , 158657.14285714, 200200.453125  , 116916.66666667,
       182697.43589744, 200200.453125  , 122375.33333333, 219625.        ,
       153761.53846154, 116916.66666667, 262766.66666667, 171800.        ,
       148896.33333333, 213300.        , 267000.        , 145375.        ,
       118350.325     , 254860.        , 118350.325     , 301500.        ,
       118350.325     , 207752.4       , 118350.325     , 118350.325     ,
       378626.        , 130069.23076923, 133097.22222222, 156877.5       ,
       139380.33333333, 426500.        , 139380.33333333, 218512.47826087,
       200200.453125  , 143194.59459459, 140444.44444444, 118350.325     ,
        68400.        , 143194.59459459, 296092.33333333, 368737.66666667,
       372402.        , 242500.        , 133097.22222222, 340000.        ,
       139380.33333333, 182697.43589744, 148896.33333333, 148973.        ,
       116916.66666667,  90200.        , 415298.        , 171800.        ,
       267000.        , 315750.        , 143194.59459459, 118350.325     ,
        88421.42857143,  60000.        , 171750.        , 118350.325     ,
       156877.5       , 148896.33333333, 263435.        , 200200.453125  ,
       139380.33333333, 182633.75      , 130069.23076923, 130069.23076923,
       139380.33333333, 250000.        , 130069.23076923, 181108.        ,
       180878.35      , 172065.        , 237615.2       , 244400.        ,
       110000.        , 200200.453125  , 198583.33333333, 200200.453125  ,
       172000.        , 136900.        , 133097.22222222, 271625.33333333,
       124000.        , 170000.        ,  58166.66666667, 149375.        ,
       133097.22222222, 152950.        , 200200.453125  , 118350.325     ,
       116916.66666667, 116916.66666667, 156877.5       , 239428.5       ,
       151900.        , 126600.        , 182697.43589744, 174814.28571429,
       171893.18181818, 108000.        , 229781.        , 100840.32258065,
       143194.59459459, 200100.        , 182633.75      , 372500.        ,
       200200.453125  , 134950.        ,  77250.        , 321500.        ,
       397495.        , 139380.33333333, 218512.47826087, 625000.        ,
       426500.        , 171750.        , 156877.5       , 133206.25      ,
       126730.        , 133097.22222222])

In [60]:
y_val

892     154500
1105    325000
413     115000
522     159000
1036    315500
         ...
526     132000
101     178000
1092    136500
411     145000
1392    123000
Name: SalePrice, Length: 146, dtype: int64

In [61]:
len(eval_predicted), len(y_val), type(eval_predicted), type(y_val)

(146, 146, numpy.ndarray, pandas.core.series.Series)

search command : MSE on 2 arrays python

link : https://www.statology.org/mean-squared-error-python/

In [62]:
import numpy as np

def mse(actual, pred): 
    actual, pred = np.array(actual), np.array(pred)
    return np.square(np.subtract(actual,pred)).mean() 

print(mse(y_val, eval_predicted))

1444715481.1064324

In [63]:
SalePrice_decision_tree = regressor.predict(df_test_without_nan_numerical_only)
SalePrice_decision_tree

array([145375.        , 145239.        , 209318.        , ...,
       148973.        , 139380.33333333, 253000.        ])

## 4.2 lightGBM

link : https://www.kaggle.com/code/ashishpatel26/light-gbm-demand-forecasting/notebook

Note : also reference from looloo computer explore folder

In [64]:
import lightgbm as lgb
from lightgbm import LGBMRegressor
from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import mean_squared_log_error

def model(train_x, train_y, test_x, test_y, test_df):

    params = {
        'nthread': 10,
        'max_depth': 5,  # Reduce max_depth for simplicity
        'boosting_type': 'gbdt',
        'objective': 'regression_l1',
        'metric': 'mape',
        'num_leaves': 8,  # Ensure num_leaves is suitable for max_depth
        'learning_rate': 0.1,
        'feature_fraction': 0.8,
        'bagging_fraction': 0.8,
        'bagging_freq': 5,
        'lambda_l1': 0.0,  # Simplify regularization
        'lambda_l2': 0.0,
        'min_child_weight': 1,
        'min_split_gain': 0.0
    }
    
    lgb_train = lgb.Dataset(train_x, train_y)
    lgb_valid = lgb.Dataset(test_x, test_y, reference=lgb_train)

    model = lgb.train(
        params, 
        lgb_train, 
        num_boost_round=1000, 
        valid_sets=[lgb_train, lgb_valid], 
        callbacks=[lgb.early_stopping(stopping_rounds=50), lgb.log_evaluation(period=50)]
    )
    
    y_test = model.predict(test_df)
    return y_test, model


SalePrice_light_gbm, model = model(X_train, y_train, X_Val, y_val, df_test_without_nan_numerical_only)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001350 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1640
[LightGBM] [Info] Number of data points in the train set: 1314, number of used features: 24
[LightGBM] [Info] Start training from score 164500.000000
Training until validation scores don't improve for 50 rounds
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	training's mape: 0.0962436	valid_1's mape: 0.110944
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	training's mape: 0.0846878	valid_1's mape: 0.104064
[150]	training's mape: 0.0789193	valid_1's mape: 0.102575
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[200]	training's mape: 0.0747934	valid_1's mape: 0.100836
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[250]	training's mape: 0.0717056	valid_1's mape: 0.100951
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Early stopping, best iteration is:
[217]	training's mape: 0.0736299	valid_1's mape: 0.100376

In [65]:
SalePrice_light_gbm

array([131840.53632163, 153934.56806104, 179294.20266377, ...,
       154581.41287421, 141804.29919344, 220155.42373582])

# 5. send test set

syntax reference from your titanic folder

In [66]:
Id = df_test["Id"]
Id

0       1461
1       1462
2       1463
3       1464
4       1465
        ...
1454    2915
1455    2916
1456    2917
1457    2918
1458    2919
Name: Id, Length: 1459, dtype: int64

## 5.1 decision tree

In [67]:
df_final = pd.DataFrame({
    "Id" : Id,
    "SalePrice" : SalePrice_decision_tree
})
df_final.to_csv("./data/house-prices-advanced-regression-techniques/submit_decision_tree.csv", index=False)
df_final

        Id      SalePrice
0     1461  145375.000000
1     1462  145239.000000
2     1463  209318.000000
3     1464  182697.435897
4     1465  188250.000000
...    ...            ...
1454  2915   77250.000000
1455  2916   77250.000000
1456  2917  148973.000000
1457  2918  139380.333333
1458  2919  253000.000000

[1459 rows x 2 columns]

## 5.2 lightgbm

In [68]:
df_final = pd.DataFrame({
    "Id" : Id,
    "SalePrice" : SalePrice_light_gbm
})
df_final.to_csv("./data/house-prices-advanced-regression-techniques/submit_light_gbm.csv", index=False)
df_final

        Id      SalePrice
0     1461  131840.536322
1     1462  153934.568061
2     1463  179294.202664
3     1464  189158.977829
4     1465  206940.447550
...    ...            ...
1454  2915   93809.052486
1455  2916   87443.096664
1456  2917  154581.412874
1457  2918  141804.299193
1458  2919  220155.423736

[1459 rows x 2 columns]